[build]
  publish = ".next"
  command = "yarn build"

# Skip all post processing in deploy previews,
# ignoring any other settings
[context.deploy-preview.processing]
  skip_processing = true

# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# [[headers]]
#   for = "*.js" # js files should be set this way
#   [headers.values]
#     Cache-Control = "public, max-age=604800, must-revalidate"
# [[headers]]
#   for = "*.css" # css files too
#   [headers.values]
#     Cache-Control = "public, max-age=604800, must-revalidate"
# [[headers]]
#   for = "/fonts/*"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.svg"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.png"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.jpg"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.jpeg"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.webp"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.gif"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.mp4"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.wav"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.ogg"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.clb"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.gltf"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.fvg"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.mp3"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
# [[headers]]
#   for = "*.webm"
#   [headers.values]
#     cache-control = "public, max-age=365000000, immutable"
